# Generated by Django 4.0.2 on 2022-03-01 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cancerinfantil', '0002_guerrero_republica_delete_casosguerreroverificados'),
    ]

    operations = [
        migrations.DeleteModel(
            name='republica',
        ),
    ]
