# Generated by Django 4.0.2 on 2022-03-10 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cancerinfantil', '0005_republicaapi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='guerrero',
        ),
        migrations.AlterModelTable(
            name='republica',
            table='Casostocsv',
        ),
        migrations.AlterModelTable(
            name='republicaapi',
            table='CasosRepublicaMex',
        ),
    ]
