# Generated by Django 4.0.2 on 2022-03-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='mensaje',
            field=models.CharField(max_length=1000),
        ),
    ]
